---
# tasks file for backup
- name: Install cronie (cron package)
  yum:
    name: cronie
    state: present

- name: Create backup directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0755'

- name: Setup hourly cron job to backup notes.db
  cron:
    name: "backup notes.db"
    minute: "0"
    hour: "*"
    user: ec2-user
    job: "cp {{ app_path }}/notes.db {{ backup_dir }}/notes_$(date +\\%F_\\%H-\\%M).db"
